# PrISMa_API

### Load Library

In [1]:
import prisma_api

### Initialise API class

In [ ]:
api = prisma_api.init()
# from prisma_api.config import update_dev_mode
# update_dev_mode(False)
# api = prisma_api.init()

### Gather MOF data from API

In [3]:
api.get_mofs()

Empty DataFrame
Columns: []
Index: []

### Gather Carbon Isotherm data from API (using dynamic filtering)

In [4]:
api.get_carbon_isotherms({'molecule': 'CO2', 'good_structure': False})

Empty DataFrame
Columns: []
Index: []

# TESTS

### adsorption_singlepoint

Load sample data for upload

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('../../AutoPrism/results/adsorption_singlepoint.csv')
api.update_adsorption_singlepoint(df)

{'created_count': 0,
 'updated_count': 995,
 'error_count': 0,
 'created_records': [],
 'updated_records': [{'id': 1211,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000384,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1212,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.001683,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 8.35155e-05,
   'avg_number_of_molecules': 0.0013},
  {'id': 1213,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.997933,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1214,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000384,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1215,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.003366,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0001927281,
   'avg_number_of_molecules': 0.003},
  {'id': 1216,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.99625,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1217,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000381,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1218,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.010439,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0006038815,
   'avg_number_of_molecules': 0.0094},
  {'id': 1219,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.98918,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1220,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_dry',
   'mixture': 'mineralization_dry',
   'config_hash': '87ebea8fd22a64ffef305106d14164469552372b',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000385,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1221,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'mixture_id': 'mineralization_dry',
   'mixture': 'mineralization_dry',
   'config_hash': '87ebea8fd22a64ffef305106d14164469552372b',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2',
   'mol_fraction': 0.999615,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0,
   'avg_number_of_molecules': 0.0},
  {'id': 1222,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000384,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0006269252,
   'avg_number_of_molecules': 0.01865},
  {'id': 1223,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.001683,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.000635329,
   'avg_number_of_molecules': 0.0189},
  {'id': 1224,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.997933,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.2681257,
   'avg_number_of_molecules': 7.9763},
  {'id': 1225,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000384,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.000606756,
   'avg_number_of_molecules': 0.01805},
  {'id': 1226,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.003366,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.001198385,
   'avg_number_of_molecules': 0.03565},
  {'id': 1227,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.99625,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.2646246,
   'avg_number_of_molecules': 7.87215},
  {'id': 1228,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000381,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0005479293,
   'avg_number_of_molecules': 0.0163},
  {'id': 1229,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.010439,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.003623729,
   'avg_number_of_molecules': 0.1078},
  {'id': 1230,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.98918,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.2614446,
   'avg_number_of_molecules': 7.77755},
  {'id': 1231,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_dry',
   'mixture': 'mineralization_dry',
   'config_hash': '87ebea8fd22a64ffef305106d14164469552372b',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000385,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0005697792,
   'avg_number_of_molecules': 0.01695},
  {'id': 1232,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'mixture_id': 'mineralization_dry',
   'mixture': 'mineralization_dry',
   'config_hash': '87ebea8fd22a64ffef305106d14164469552372b',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2',
   'mol_fraction': 0.999615,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.2651742,
   'avg_number_of_molecules': 7.8885},
  {'id': 1233,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000384,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0006153226,
   'avg_number_of_molecules': 0.0057},
  {'id': 1234,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.001683,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0006962861,
   'avg_number_of_molecules': 0.00645},
  {'id': 1235,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_RH10',
   'mixture': 'mineralization_RH10',
   'config_hash': '6e18fe4ed66d8e90c2e2a4efeec2b737d321cc98',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.997933,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.2838041,
   'avg_number_of_molecules': 2.629},
  {'id': 1236,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000384,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.0006369129,
   'avg_number_of_molecules': 0.0059},
  {'id': 1237,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'H2O',
   'component_label': 'H2O',
   'mol_fraction': 0.003366,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.00124144,
   'avg_number_of_molecules': 0.0115},
  {'id': 1238,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_RH20',
   'mixture': 'mineralization_RH20',
   'config_hash': '2c91aabca41eca24c02cb2a7509fe106d79763dc',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'N2',
   'component_label': 'N2*',
   'mol_fraction': 0.99625,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': True,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'absolute_loading_mol_kg': 0.2851858,
   'avg_number_of_molecules': 2.6418},
  {'id': 1239,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'mixture_id': 'mineralization_wet',
   'mixture': 'mineralization_RH60',
   'config_hash': 'a1213b28f8e092a146dd9232a5673b34ae5803ef',
   'temperature_K': 288.15,
   'pressure_bar': 1.01325,
   'component': 'CO2',
   'component_label': 'CO2',
   'mol_fraction': 0.000381,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,

In [7]:
df = pd.read_csv('../../AutoPrism/results/heat_capacity_all_tidy.csv')
api.update_heat_capacity_all_tidy(df)

{'created_count': 0,
 'updated_count': 297,
 'error_count': 0,
 'created_records': [],
 'updated_records': [{'id': 274,
   'structure': '05000N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9504490424,
   'Cv_gravimetric_std': 0.0067526597,
   'Cv_molar_mean': 8.806371,
   'Cv_molar_std': 0.06256662},
  {'id': 275,
   'structure': '05000N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9877726606,
   'Cv_gravimetric_std': 0.0165762333,
   'Cv_molar_mean': 9.152191,
   'Cv_molar_std': 0.15358692},
  {'id': 276,
   'structure': '05000N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3508411517,
   'Cv_gravimetric_std': 0.0073491172,
   'Cv_molar_mean': 12.516195,
   'Cv_molar_std': 0.06809314},
  {'id': 277,
   'structure': '05001N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9134831525,
   'Cv_gravimetric_std': 0.0034719791,
   'Cv_molar_mean': 8.84582,
   'Cv_molar_std': 0.03362133},
  {'id': 278,
   'structure': '05001N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9460689268,
   'Cv_gravimetric_std': 0.0051291879,
   'Cv_molar_mean': 9.161367,
   'Cv_molar_std': 0.049669106},
  {'id': 279,
   'structure': '05001N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.2989612504,
   'Cv_gravimetric_std': 0.0028943488,
   'Cv_molar_mean': 12.578642,
   'Cv_molar_std': 0.02802775},
  {'id': 280,
   'structure': '07000N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.941810283,
   'Cv_gravimetric_std': 0.0035872851,
   'Cv_molar_mean': 8.655049,
   'Cv_molar_std': 0.032966483},
  {'id': 281,
   'structure': '07000N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9790641003,
   'Cv_gravimetric_std': 0.0060967956,
   'Cv_molar_mean': 8.997405,
   'Cv_molar_std': 0.056028366},
  {'id': 282,
   'structure': '07000N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3438815609,
   'Cv_gravimetric_std': 0.0022289087,
   'Cv_molar_mean': 12.350005,
   'Cv_molar_std': 0.020483037},
  {'id': 283,
   'structure': '07001N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.8908432138,
   'Cv_gravimetric_std': 0.0033524744,
   'Cv_molar_mean': 9.030556,
   'Cv_molar_std': 0.033984214},
  {'id': 284,
   'structure': '07001N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9254381494,
   'Cv_gravimetric_std': 0.0023763542,
   'Cv_molar_mean': 9.381247,
   'Cv_molar_std': 0.024089215},
  {'id': 285,
   'structure': '07001N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.2598740882,
   'Cv_gravimetric_std': 0.0023055153,
   'Cv_molar_mean': 12.771454,
   'Cv_molar_std': 0.023371257},
  {'id': 286,
   'structure': '08000N3_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.086318928,
   'Cv_gravimetric_std': 0.0096268824,
   'Cv_molar_mean': 8.596348,
   'Cv_molar_std': 0.07618025},
  {'id': 287,
   'structure': '08000N3_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.128669263,
   'Cv_gravimetric_std': 0.0091362087,
   'Cv_molar_mean': 8.9314785,
   'Cv_molar_std': 0.07229739},
  {'id': 288,
   'structure': '08000N3_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.499937909,
   'Cv_gravimetric_std': 0.0028839818,
   'Cv_molar_mean': 11.869432,
   'Cv_molar_std': 0.022821696},
  {'id': 289,
   'structure': '15070N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9977275515,
   'Cv_gravimetric_std': 0.0057788157,
   'Cv_molar_mean': 8.262909,
   'Cv_molar_std': 0.047858667},
  {'id': 290,
   'structure': '15070N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0417371801,
   'Cv_gravimetric_std': 0.0072071819,
   'Cv_molar_mean': 8.627384,
   'Cv_molar_std': 0.059688047},
  {'id': 291,
   'structure': '15070N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.4321308577,
   'Cv_gravimetric_std': 0.0048857969,
   'Cv_molar_mean': 11.8605175,
   'Cv_molar_std': 0.040462933},
  {'id': 292,
   'structure': '16057N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.8535140889,
   'Cv_gravimetric_std': 0.0050184007,
   'Cv_molar_mean': 9.577814,
   'Cv_molar_std': 0.056314547},
  {'id': 293,
   'structure': '16057N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.8842819244,
   'Cv_gravimetric_std': 0.0064068825,
   'Cv_molar_mean': 9.923079,
   'Cv_molar_std': 0.071895674},
  {'id': 294,
   'structure': '16057N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.1828500289,
   'Cv_gravimetric_std': 0.0059609464,
   'Cv_molar_mean': 13.273499,
   'Cv_molar_std': 0.06689148},
  {'id': 295,
   'structure': '17150N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.06343769,
   'Cv_gravimetric_std': 0.0023832607,
   'Cv_molar_mean': 8.177443,
   'Cv_molar_std': 0.018326288},
  {'id': 296,
   'structure': '17150N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.103414038,
   'Cv_gravimetric_std': 0.0021784341,
   'Cv_molar_mean': 8.484846,
   'Cv_molar_std': 0.016751535},
  {'id': 297,
   'structure': '17150N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.5065739501,
   'Cv_gravimetric_std': 0.0025756946,
   'Cv_molar_mean': 11.584997,
   'Cv_molar_std': 0.01980617},
  {'id': 298,
   'structure': '19020N3_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9738637821,
   'Cv_gravimetric_std': 0.0107779478,
   'Cv_molar_mean': 9.013264,
   'Cv_molar_std': 0.09975162},
  {'id': 298,
   'structure': '19020N3_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9738637821,
   'Cv_gravimetric_std': 0.0107779478,
   'Cv_molar_mean': 9.013264,
   'Cv_molar_std': 0.09975162},
  {'id': 299,
   'structure': '19020N3_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0042580873,
   'Cv_gravimetric_std': 0.0152906271,
   'Cv_molar_mean': 9.294569,
   'Cv_molar_std': 0.14151733},
  {'id': 299,
   'structure': '19020N3_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0042580873,
   'Cv_gravimetric_std': 0.0152906271,
   'Cv_molar_mean': 9.294569,
   'Cv_molar_std': 0.14151733},
  {'id': 300,
   'structure': '19020N3_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3303563562,
   'Cv_gravimetric_std': 0.0184799893,
   'Cv_molar_mean': 12.312659,
   'Cv_molar_std': 0.17103526},
  {'id': 300,
   'structure': '19020N3_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3303563562,
   'Cv_gravimetric_std': 0.0184799893,
   'Cv_molar_mean': 12.312659,
   'Cv_molar_std': 0.17103526},
  {'id': 301,
   'structure': '20051N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9576980051,
   'Cv_gravimetric_std': 0.0032212753,
   'Cv_molar_mean': 8.58261,
   'Cv_molar_std': 0.028868046},
  {'id': 301,
   'structure': '20051N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9576980051,
   'Cv_gravimetric_std': 0.0032212753,
   'Cv_molar_mean': 8.58261,
   'Cv_molar_std': 0.028868046},
  {'id': 302,
   'structure': '20051N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9969858313,
   'Cv_gravimetric_std': 0.0053635316,
   'Cv_molar_mean': 8.934696,
   'Cv_molar_std': 0.04806636},
  {'id': 302,
   'structure': '20051N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9969858313,
   'Cv_gravimetric_std': 0.0053635316,
   'Cv_molar_mean': 8.934696,
   'Cv_molar_std': 0.04806636},
  {'id': 303,
   'structure': '20051N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3522195111,
   'Cv_gravimetric_std': 0.002144001,
   'Cv_molar_mean': 12.1181965,
   'Cv_molar_std': 0.019214053},
  {'id': 303,
   'structure': '20051N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3522195111,
   'Cv_gravimetric_std': 0.002144001,
   'Cv_molar_mean': 12.1181965,
   'Cv_molar_std': 0.019214053},
  {'id': 304,
   'structure': '20590N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9625276335,
   'Cv_gravimetric_std': 0.0074902333,
   'Cv_molar_mean': 8.59376,
   'Cv_molar_std': 0.06687535},
  {'id': 304,
   'structure': '20590N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9625276335,
   'Cv_gravimetric_std': 0.0074902333,
   'Cv_molar_mean': 8.59376,
   'Cv_molar_std': 0.06687535},
  {'id': 305,
   'structure': '20590N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9996324844,
   'Cv_gravimetric_std': 0.0074719298,
   'Cv_molar_mean': 8.925043,
   'Cv_molar_std': 0.06671171},
  {'id': 305,
   'structure': '20590N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.9996324844,
   'Cv_gravimetric_std': 0.0074719298,
   'Cv_molar_mean': 8.925043,
   'Cv_molar_std': 0.06671171},
  {'id': 306,
   'structure': '20590N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3639931327,
   'Cv_gravimetric_std': 0.0044384044,
   'Cv_molar_mean': 12.178173,
   'Cv_molar_std': 0.039627746},
  {'id': 306,
   'structure': '20590N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3639931327,
   'Cv_gravimetric_std': 0.0044384044,
   'Cv_molar_mean': 12.178173,
   'Cv_molar_std': 0.039627746},
  {'id': 307,
   'structure': '21030N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.0108740976,
   'Cv_gravimetric_std': 0.0025927691,
   'Cv_molar_mean': 8.096626,
   'Cv_molar_std': 0.020766966},
  {'id': 308,
   'structure': '21030N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0519863392,
   'Cv_gravimetric_std': 0.0041622798,
   'Cv_molar_mean': 8.425915,
   'Cv_molar_std': 0.033337887},
  {'id': 309,
   'structure': '21030N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.4583937912,
   'Cv_gravimetric_std': 0.0028486854,
   'Cv_molar_mean': 11.681048,
   'Cv_molar_std': 0.022816781},
  {'id': 310,
   'structure': '22108N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.0111819629,
   'Cv_gravimetric_std': 0.002474929,
   'Cv_molar_mean': 8.127898,
   'Cv_molar_std': 0.019893512},
  {'id': 310,
   'structure': '22108N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.0111819629,
   'Cv_gravimetric_std': 0.002474929,
   'Cv_molar_mean': 8.127898,
   'Cv_molar_std': 0.019893512},
  {'id': 311,
   'structure': '22108N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0575112825,
   'Cv_gravimetric_std': 0.0028383918,
   'Cv_molar_mean': 8.500295,
   'Cv_molar_std': 0.022815065},
  {'id': 311,
   'structure': '22108N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0575112825,
   'Cv_gravimetric_std': 0.0028383918,
   'Cv_molar_mean': 8.500295,
   'Cv_molar_std': 0.022815065},
  {'id': 312,
   'structure': '22108N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.4571029683,
   'Cv_gravimetric_std': 0.0016512971,
   'Cv_molar_mean': 11.712219,
   'Cv_molar_std': 0.013273282},
  {'id': 312,
   'structure': '22108N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.4571029683,
   'Cv_gravimetric_std': 0.0016512971,
   'Cv_molar_mean': 11.712219,
   'Cv_molar_std': 0.013273282},
  {'id': 313,
   'structure': '22221N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.0376494808,
   'Cv_gravimetric_std': 0.004197603,
   'Cv_molar_mean': 8.4235935,
   'Cv_molar_std': 0.03407599},
  {'id': 313,
   'structure': '22221N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 1.0376494808,
   'Cv_gravimetric_std': 0.004197603,
   'Cv_molar_mean': 8.4235935,
   'Cv_molar_std': 0.03407599},
  {'id': 314,
   'structure': '22221N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0831200693,
   'Cv_gravimetric_std': 0.0028824009,
   'Cv_molar_mean': 8.792722,
   'Cv_molar_std': 0.023399236},
  {'id': 314,
   'structure': '22221N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0831200693,
   'Cv_gravimetric_std': 0.0028824009,
   'Cv_molar_mean': 8.792722,
   'Cv_molar_std': 0.023399236},
  {'id': 315,
   'structure': '22221N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.4687855579,
   'Cv_gravimetric_std': 0.0039677057,
   'Cv_molar_mean': 11.923536,
   'Cv_molar_std': 0.032209594},
  {'id': 315,
   'structure': '22221N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.4687855579,
   'Cv_gravimetric_std': 0.0039677057,
   'Cv_molar_mean': 11.923536,
   'Cv_molar_std': 0.032209594},
  {'id': 316,
   'structure': '22551N2_ddec.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9716264374,
   'Cv_gravimetric_std': 0.0020058756,
   'Cv_molar_mean': 8.229108,
   'Cv_molar_std': 0.016988723},
  {'id': 317,
   'structure': '22551N2_ddec.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 1.0140546459,
   'Cv_gravimetric_std': 0.0030954553,
   'Cv_molar_mean': 8.5884495,
   'Cv_molar_std': 0.026216764},
  {'id': 318,
   'structure': '22551N2_ddec.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.3959510054,
   'Cv_gravimetric_std': 0.0015361779,
   'Cv_molar_mean': 11.822887,
   'Cv_molar_std': 0.013010641},
  {'id': 319,
   'structure': 'ASEJOZ.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.5939817779,
   'Cv_gravimetric_std': 0.0062452109,
   'Cv_molar_mean': 11.044222,
   'Cv_molar_std': 0.116120584},
  {'id': 320,
   'structure': 'ASEJOZ.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.6108045576,
   'Cv_gravimetric_std': 0.0078543433,
   'Cv_molar_mean': 11.357016,
   'Cv_molar_std': 0.14604005},
  {'id': 321,
   'structure': 'ASEJOZ.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 0.7716119624,
   'Cv_gravimetric_std': 0.0037703175,
   'Cv_molar_mean': 14.346994,
   'Cv_molar_std': 0.0701035},
  {'id': 322,
   'structure': 'ASEJOZ01_clean.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.6129018151,
   'Cv_gravimetric_std': 0.0125993991,
   'Cv_molar_mean': 11.396012,
   'Cv_molar_std': 0.23426747},
  {'id': 323,
   'structure': 'ASEJOZ01_clean.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.6126930798,
   'Cv_gravimetric_std': 0.0121592701,
   'Cv_molar_mean': 11.39213,
   'Cv_molar_std': 0.22608371},
  {'id': 324,
   'structure': 'ASEJOZ01_clean.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 0.7572462629,
   'Cv_gravimetric_std': 0.014135715,
   'Cv_molar_mean': 14.0798855,
   'Cv_molar_std': 0.2628329},
  {'id': 325,
   'structure': 'AWASAU_clean.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.4353461749,
   'Cv_gravimetric_std': 0.0141208934,
   'Cv_molar_mean': 11.509592,
   'Cv_molar_std': 0.37332538},
  {'id': 326,
   'structure': 'AWASAU_clean.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.4223548953,
   'Cv_gravimetric_std': 0.0143733671,
   'Cv_molar_mean': 11.166129,
   'Cv_molar_std': 0.38},
  {'id': 327,
   'structure': 'AWASAU_clean.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 0.5293317725,
   'Cv_gravimetric_std': 0.0134197293,
   'Cv_molar_mean': 13.994362,
   'Cv_molar_std': 0.35478795},
  {'id': 328,
   'structure': 'AWASOI_clean.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.4372232026,
   'Cv_gravimetric_std': 0.0113498556,
   'Cv_molar_mean': 11.559215,
   'Cv_molar_std': 0.30006504},
  {'id': 329,
   'structure': 'AWASOI_clean.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.4222532304,
   'Cv_gravimetric_std': 0.0141507844,
   'Cv_molar_mean': 11.163443,
   'Cv_molar_std': 0.37411547},
  {'id': 330,
   'structure': 'AWASOI_clean.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 0.528203162,
   'Cv_gravimetric_std': 0.0143534779,
   'Cv_molar_mean': 13.964523,
   'Cv_molar_std': 0.37947437},
  {'id': 331,
   'structure': 'BETGUE_clean.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.734361898,
   'Cv_gravimetric_std': 0.0195106413,
   'Cv_molar_mean': 10.58634,
   'Cv_molar_std': 0.28125936},
  {'id': 332,
   'structure': 'BETGUE_clean.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.7251295664,
   'Cv_gravimetric_std': 0.0188111571,
   'Cv_molar_mean': 10.453249,
   'Cv_molar_std': 0.27117592},
  {'id': 333,
   'structure': 'BETGUE_clean.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 0.9438735858,
   'Cv_gravimetric_std': 0.0242960858,
   'Cv_molar_mean': 13.606598,
   'Cv_molar_std': 0.35024503},
  {'id': 334,
   'structure': 'CANRUG_clean.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.9119627058,
   'Cv_gravimetric_std': 0.0408771433,
   'Cv_molar_mean': 9.360062,
   'Cv_molar_std': 0.4195485},
  {'id': 335,
   'structure': 'CANRUG_clean.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.8983508907,
   'Cv_gravimetric_std': 0.0293791816,
   'Cv_molar_mean': 9.220355,
   'Cv_molar_std': 0.30153742},
  {'id': 336,
   'structure': 'CANRUG_clean.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 1.1823855266,
   'Cv_gravimetric_std': 0.0402898313,
   'Cv_molar_mean': 12.135585,
   'Cv_molar_std': 0.4135205},
  {'id': 337,
   'structure': 'COCNAL_clean.cif',
   'temperature_K': 288.15,
   'temperature_C': 15.0,
   'Cv_gravimetric_mean': 0.7068361531,
   'Cv_gravimetric_std': 0.0221748318,
   'Cv_molar_mean': 9.306017,
   'Cv_molar_std': 0.29194808},
  {'id': 338,
   'structure': 'COCNAL_clean.cif',
   'temperature_K': 300.0,
   'temperature_C': 26.85,
   'Cv_gravimetric_mean': 0.6966839139,
   'Cv_gravimetric_std': 0.020320778,
   'Cv_molar_mean': 9.172356,
   'Cv_molar_std': 0.26753795},
  {'id': 339,
   'structure': 'COCNAL_clean.cif',
   'temperature_K': 423.15,
   'temperature_C': 150.0,
   'Cv_gravimetric_mean': 0.9345383518,
   'Cv_gravimetric_std': 0.0251299243,
   'Cv_molar_mean': 12.3038845,

In [8]:
df = pd.read_csv('../../AutoPrism/results/isotherm_H2.csv')
api.update_isotherm_h2(df)

{'created_count': 0,
 'updated_count': 33,
 'error_count': 0,
 'created_records': [],
 'updated_records': [{'id': 34,
   'structure': 'RSM1045.cif',
   'md5': 'b0cd85b58291c495ba191996ae70fd9b',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.407514,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 14.4259956,
   'absolute_loading_mol_kg': 0.5405547,
   'avg_number_of_molecules': 18.75245,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.792868,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.5759264999},
  {'id': 35,
   'structure': 'RSM1045.cif',
   'md5': 'b0cd85b58291c495ba191996ae70fd9b',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.407514,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 14.4259956,
   'absolute_loading_mol_kg': 2.643036,
   'avg_number_of_molecules': 91.6899,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.915864,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.6989224999},
  {'id': 36,
   'structure': 'RSM1045.cif',
   'md5': 'b0cd85b58291c495ba191996ae70fd9b',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 50.0,
   'framework_charge_origin': 'CIF_File',
   'framework_cif_has_atom_site_charge': True,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.407514,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 14.4259956,
   'absolute_loading_mol_kg': 3.846053,
   'avg_number_of_molecules': 133.4239,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.973504,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.7565624999},
  {'id': 37,
   'structure': 'koslub_P1_fixed.cif',
   'md5': 'ceed6438ea2618a6ec762a0bc806a8b6',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.491646,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 17.4042684,
   'absolute_loading_mol_kg': 0.4180808,
   'avg_number_of_molecules': 18.75265,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -5.336685,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -8.1197434999},
  {'id': 38,
   'structure': 'koslub_P1_fixed.cif',
   'md5': 'ceed6438ea2618a6ec762a0bc806a8b6',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.491646,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 17.4042684,
   'absolute_loading_mol_kg': 2.215609,
   'avg_number_of_molecules': 99.3792,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -5.356966,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -8.1400244999},
  {'id': 39,
   'structure': 'koslub_P1_fixed.cif',
   'md5': 'ceed6438ea2618a6ec762a0bc806a8b6',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 50.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.491646,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 17.4042684,
   'absolute_loading_mol_kg': 3.390615,
   'avg_number_of_molecules': 152.0831,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -5.4329,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -8.2159584999},
  {'id': 40,
   'structure': 'qmof-0a464a7.cif',
   'md5': '84efd9f132bedab343ff77e2437329a0',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.669413,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 23.6972202,
   'absolute_loading_mol_kg': 0.9973536,
   'avg_number_of_molecules': 17.031,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -7.282536,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -10.0655944999},
  {'id': 41,
   'structure': 'qmof-0a464a7.cif',
   'md5': '84efd9f132bedab343ff77e2437329a0',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.669413,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 23.6972202,
   'absolute_loading_mol_kg': 4.481427,
   'avg_number_of_molecules': 76.5257,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.799204,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.5822624999},
  {'id': 42,
   'structure': 'qmof-0a464a7.cif',
   'md5': '84efd9f132bedab343ff77e2437329a0',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 50.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.669413,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 23.6972202,
   'absolute_loading_mol_kg': 6.44618,
   'avg_number_of_molecules': 110.0762,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.657303,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.4403614999},
  {'id': 43,
   'structure': 'qmof-1da6c76.cif',
   'md5': 'b1dd762e1662df50a8c893131ae9cb11',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.52665,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 89.44341,
   'absolute_loading_mol_kg': 1.143754,
   'avg_number_of_molecules': 8.9258,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.598754,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.3818124999},
  {'id': 44,
   'structure': 'qmof-1da6c76.cif',
   'md5': 'b1dd762e1662df50a8c893131ae9cb11',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.52665,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 89.44341,
   'absolute_loading_mol_kg': 6.409495,
   'avg_number_of_molecules': 50.0194,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.616653,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.3997114999},
  {'id': 45,
   'structure': 'qmof-1da6c76.cif',
   'md5': 'b1dd762e1662df50a8c893131ae9cb11',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 50.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.52665,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 89.44341,
   'absolute_loading_mol_kg': 10.31323,
   'avg_number_of_molecules': 80.484,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.645609,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.4286674999},
  {'id': 46,
   'structure': 'qmof-3beea42.cif',
   'md5': 'd151c224aed78554fad428c25f1b3124',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.755691,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 26.7514614,
   'absolute_loading_mol_kg': 0.9216785,
   'avg_number_of_molecules': 15.46635,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.546796,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.3298544999},
  {'id': 47,
   'structure': 'qmof-3beea42.cif',
   'md5': 'd151c224aed78554fad428c25f1b3124',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.755691,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 26.7514614,
   'absolute_loading_mol_kg': 4.559753,
   'avg_number_of_molecules': 76.51555,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.644323,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.4273814999},
  {'id': 48,
   'structure': 'qmof-3beea42.cif',
   'md5': 'd151c224aed78554fad428c25f1b3124',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 50.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 0.755691,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 26.7514614,
   'absolute_loading_mol_kg': 6.782253,
   'avg_number_of_molecules': 113.8105,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -6.655317,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -9.4383754999},
  {'id': 49,
   'structure': 'qmof-798e431.cif',
   'md5': '853c87c73a38c205d09c91658fda10f8',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.70945,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 95.91453,
   'absolute_loading_mol_kg': 1.188169,
   'avg_number_of_molecules': 16.7569,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.508371,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.2914294999},
  {'id': 50,
   'structure': 'qmof-798e431.cif',
   'md5': '853c87c73a38c205d09c91658fda10f8',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.70945,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 95.91453,
   'absolute_loading_mol_kg': 6.756798,
   'avg_number_of_molecules': 95.292,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.489736,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.2727944999},
  {'id': 51,
   'structure': 'qmof-798e431.cif',
   'md5': '853c87c73a38c205d09c91658fda10f8',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 50.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.70945,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 95.91453,
   'absolute_loading_mol_kg': 10.88375,
   'avg_number_of_molecules': 153.495,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.521238,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.3042964999},
  {'id': 52,
   'structure': 'qmof-7c567fa.cif',
   'md5': '650007ea35848e188b1dc4c34efe99ab',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': 'd041cce19d10cded485f2f42588a7d9a2de9a0a6',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 5.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.38533,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 84.440682,
   'absolute_loading_mol_kg': 1.091537,
   'avg_number_of_molecules': 11.14755,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.598592,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.3816504999},
  {'id': 53,
   'structure': 'qmof-7c567fa.cif',
   'md5': '650007ea35848e188b1dc4c34efe99ab',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '46177ba2bbcd7e598fbae3b2e92ef4a992302a87',
   'mode': 'gcmc',
   'component': 'H2',
   'temperature_K': 223.15,
   'pressure_bar': 30.0,
   'framework_charge_origin': 'ChargeEquilibration',
   'framework_cif_has_atom_site_charge': False,
   'charge_method': 'Ewald',
   'ewald_precision': None,
   'component_is_charged': False,
   'component_charge_origin': 'force_field.json:PseudoAtoms',
   'poav_cm3_per_g': 2.38533,
   'molsatdens_mol_L': 35.4,
   'estimated_saturation_loading_mol_kg': 84.440682,
   'absolute_loading_mol_kg': 6.133979,
   'avg_number_of_molecules': 62.64455,
   'henry_mol_kg_Pa': None,
   'henry_unit': None,
   'enthalpy_of_adsorption_kJ_mol': -3.670001,
   'ideal_gas_energy_kJ_mol': 2.7830584999,
   'heat_of_adsorption_kJ_mol': -6.4530594999},
  {'id': 54,
   'structure': 'qmof-7c567fa.cif',
   'md5': '650007ea35848e188b1dc4c34efe99ab',
   'isotherm_id': 'h2_lowp_minus50C',
   'isotherm': 'H2 low-pressure (-50 °C): 5/30/50 bar',
   'config_hash': '4609dc6e9ccf7035b6d79b9e923aa5fae12b836c',
   'mode': 'gcmc',
   'component': 'H2',

In [9]:
df = pd.read_csv('../../AutoPrism/results/mofchecker.csv')
api.update_mofchecker(df)

{'created_count': 0,
 'updated_count': 91,
 'error_count': 0,
 'created_records': [],
 'updated_records': [{'id': 92,
   'structure': '05000N2_ddec.cif',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 93,
   'structure': '05001N2_ddec.cif',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 94,
   'structure': '07000N2_ddec.cif',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 95,
   'structure': '07001N2_ddec.cif',
   'md5': '07efdb27d3ccf4e78e03da044906f917',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 96,
   'structure': '08000N3_ddec.cif',
   'md5': '1da8a7bc1aa56632455c6c2b643c2d7c',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 97,
   'structure': '15070N2_ddec.cif',
   'md5': 'c5c5b4ebd33465b24ded58a5d4f49b24',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 98,
   'structure': '16057N2_ddec.cif',
   'md5': '6202432f901e6b6d68c4dd3bc2ce866c',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 99,
   'structure': '17150N2_ddec.cif',
   'md5': 'dcc908a9605f5f513d6a7a1d220b25ef',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 100,
   'structure': '19020N3_ddec.cif',
   'md5': '9d1d4333c36c84121f85fd95f7112c6e',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:37Z'},
  {'id': 101,
   'structure': '20051N2_ddec.cif',
   'md5': '7409057b99b5ac68066d923ded4ca2a8',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '7409057b99b5ac68066d923ded4ca2a8_mofchecker.json',
   'mofchecker_log': 'logs/7409057b99b5ac68066d923ded4ca2a8_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:31:44Z'},
  {'id': 102,
   'structure': '20590N2_ddec.cif',
   'md5': '735702b3d8c787aa19784f8b53bb6c9e',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:44Z'},
  {'id': 103,
   'structure': '21030N2_ddec.cif',
   'md5': '7366b13430080588504f0bf8bd2a387f',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:44Z'},
  {'id': 104,
   'structure': '22108N2_ddec.cif',
   'md5': 'b658efcf311744888b772d09151f8e92',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:44Z'},
  {'id': 105,
   'structure': '22221N2_ddec.cif',
   'md5': '544145e69898ec2ce922aaf64b32bafa',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:44Z'},
  {'id': 106,
   'structure': '22551N2_ddec.cif',
   'md5': 'd3e2466eb9415ff422be4bea2e1a074a',
   'is_mof': False,
   'MOFQ': False,
   'mofq_reason': 'fast_non_mof:no_metal_atoms',
   'mofchecker_blob': None,
   'mofchecker_log': None,
   'mofchecker_updated_at': '2026-01-20T18:31:44Z'},
  {'id': 107,
   'structure': 'ASEJOZ.cif',
   'md5': 'cc5178b74a53bf9ec963c6df0fde4c6e',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'cc5178b74a53bf9ec963c6df0fde4c6e_mofchecker.json',
   'mofchecker_log': 'logs/cc5178b74a53bf9ec963c6df0fde4c6e_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:31:49Z'},
  {'id': 108,
   'structure': 'ASEJOZ01_clean.cif',
   'md5': '08759f403a58b6b0a11029bc8cb2551d',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '08759f403a58b6b0a11029bc8cb2551d_mofchecker.json',
   'mofchecker_log': 'logs/08759f403a58b6b0a11029bc8cb2551d_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:31:53Z'},
  {'id': 109,
   'structure': 'AWASAU_clean.cif',
   'md5': '7a1f8ff0a9b0555ff9a97c5895ae30a2',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '7a1f8ff0a9b0555ff9a97c5895ae30a2_mofchecker.json',
   'mofchecker_log': 'logs/7a1f8ff0a9b0555ff9a97c5895ae30a2_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:31:58Z'},
  {'id': 110,
   'structure': 'AWASOI_clean.cif',
   'md5': '5dbfdd322670ead4c997b84b2f6e4997',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '5dbfdd322670ead4c997b84b2f6e4997_mofchecker.json',
   'mofchecker_log': 'logs/5dbfdd322670ead4c997b84b2f6e4997_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:06Z'},
  {'id': 111,
   'structure': 'BETGUE_clean.cif',
   'md5': 'a1dd3ef62f00e5c1251fa7873d16f977',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'a1dd3ef62f00e5c1251fa7873d16f977_mofchecker.json',
   'mofchecker_log': 'logs/a1dd3ef62f00e5c1251fa7873d16f977_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:11Z'},
  {'id': 112,
   'structure': 'CANRUG_clean.cif',
   'md5': '24c4b2e063d1dc866baa37b97750c927',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '24c4b2e063d1dc866baa37b97750c927_mofchecker.json',
   'mofchecker_log': 'logs/24c4b2e063d1dc866baa37b97750c927_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:17Z'},
  {'id': 113,
   'structure': 'COCNAL_clean.cif',
   'md5': '6bcb6439e8f347913711b02170ec714f',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '6bcb6439e8f347913711b02170ec714f_mofchecker.json',
   'mofchecker_log': 'logs/6bcb6439e8f347913711b02170ec714f_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:27Z'},
  {'id': 114,
   'structure': 'COYTIU_clean.cif',
   'md5': '03f7703dafeb0be983c3a69dd7c4a6f3',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '03f7703dafeb0be983c3a69dd7c4a6f3_mofchecker.json',
   'mofchecker_log': 'logs/03f7703dafeb0be983c3a69dd7c4a6f3_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:31Z'},
  {'id': 115,
   'structure': 'COYTOA_clean.cif',
   'md5': '9e1ff3085eb6946df2cf2293741bbf6f',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '9e1ff3085eb6946df2cf2293741bbf6f_mofchecker.json',
   'mofchecker_log': 'logs/9e1ff3085eb6946df2cf2293741bbf6f_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:36Z'},
  {'id': 116,
   'structure': 'DATPIY_clean.cif',
   'md5': '30ff4e93f130f8fa5e34bdab55e50f91',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '30ff4e93f130f8fa5e34bdab55e50f91_mofchecker.json',
   'mofchecker_log': 'logs/30ff4e93f130f8fa5e34bdab55e50f91_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:41Z'},
  {'id': 117,
   'structure': 'DOMDAL_clean.cif',
   'md5': '1c8df5a6518a25c482f264f3bedd2162',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '1c8df5a6518a25c482f264f3bedd2162_mofchecker.json',
   'mofchecker_log': 'logs/1c8df5a6518a25c482f264f3bedd2162_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:47Z'},
  {'id': 118,
   'structure': 'DOQGUM_clean.cif',
   'md5': '6ea3e5b31fb913bef56fa95cd0b3277b',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '6ea3e5b31fb913bef56fa95cd0b3277b_mofchecker.json',
   'mofchecker_log': 'logs/6ea3e5b31fb913bef56fa95cd0b3277b_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:51Z'},
  {'id': 119,
   'structure': 'DOQHIB_clean.cif',
   'md5': 'c08661d58bb7f0074ad15203cad215dd',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'c08661d58bb7f0074ad15203cad215dd_mofchecker.json',
   'mofchecker_log': 'logs/c08661d58bb7f0074ad15203cad215dd_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:32:55Z'},
  {'id': 120,
   'structure': 'ELILER_clean.cif',
   'md5': '24f47e65b0de4fd3c8f0453923375334',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '24f47e65b0de4fd3c8f0453923375334_mofchecker.json',
   'mofchecker_log': 'logs/24f47e65b0de4fd3c8f0453923375334_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:00Z'},
  {'id': 121,
   'structure': 'EXIBUI_clean.cif',
   'md5': '912a0bd0e64ffa605348c360f16175e0',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '912a0bd0e64ffa605348c360f16175e0_mofchecker.json',
   'mofchecker_log': 'logs/912a0bd0e64ffa605348c360f16175e0_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:04Z'},
  {'id': 122,
   'structure': 'GADFAV_clean.cif',
   'md5': '30d7005e525010e1056ae50572327df1',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '30d7005e525010e1056ae50572327df1_mofchecker.json',
   'mofchecker_log': 'logs/30d7005e525010e1056ae50572327df1_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:08Z'},
  {'id': 123,
   'structure': 'GAJYUN_clean.cif',
   'md5': '51c86bd205edc3454842944b88b45fc7',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '51c86bd205edc3454842944b88b45fc7_mofchecker.json',
   'mofchecker_log': 'logs/51c86bd205edc3454842944b88b45fc7_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:12Z'},
  {'id': 124,
   'structure': 'GAJZEY_clean.cif',
   'md5': '3573f96507bc83310121a7ee0f14ea65',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '3573f96507bc83310121a7ee0f14ea65_mofchecker.json',
   'mofchecker_log': 'logs/3573f96507bc83310121a7ee0f14ea65_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:16Z'},
  {'id': 125,
   'structure': 'HOWROC_clean.cif',
   'md5': 'eac13e2d4e1d7be8f038dd0738f25f57',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'eac13e2d4e1d7be8f038dd0738f25f57_mofchecker.json',
   'mofchecker_log': 'logs/eac13e2d4e1d7be8f038dd0738f25f57_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:23Z'},
  {'id': 126,
   'structure': 'KIBDEF_clean.cif',
   'md5': 'b4345b687f3113480c5b3792a61aadaa',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'b4345b687f3113480c5b3792a61aadaa_mofchecker.json',
   'mofchecker_log': 'logs/b4345b687f3113480c5b3792a61aadaa_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:28Z'},
  {'id': 127,
   'structure': 'KIBDIJ_clean.cif',
   'md5': '8741ed541698c26e1ca962178d146e99',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '8741ed541698c26e1ca962178d146e99_mofchecker.json',
   'mofchecker_log': 'logs/8741ed541698c26e1ca962178d146e99_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:32Z'},
  {'id': 128,
   'structure': 'LADWAR_clean.cif',
   'md5': '23d096b6bcafc6dac0cbfde64cd6790f',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '23d096b6bcafc6dac0cbfde64cd6790f_mofchecker.json',
   'mofchecker_log': 'logs/23d096b6bcafc6dac0cbfde64cd6790f_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:36Z'},
  {'id': 129,
   'structure': 'LAGNAK_clean.cif',
   'md5': '5fb9d99008a2e440f74f463ac138177d',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '5fb9d99008a2e440f74f463ac138177d_mofchecker.json',
   'mofchecker_log': 'logs/5fb9d99008a2e440f74f463ac138177d_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:40Z'},
  {'id': 130,
   'structure': 'LAGQER_clean.cif',
   'md5': '623d60bfe0ef0ae4044430c63519110f',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '623d60bfe0ef0ae4044430c63519110f_mofchecker.json',
   'mofchecker_log': 'logs/623d60bfe0ef0ae4044430c63519110f_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:44Z'},
  {'id': 131,
   'structure': 'MEHMET_clean.cif',
   'md5': '1ff62550d139facd6dca5644b47d5eb2',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '1ff62550d139facd6dca5644b47d5eb2_mofchecker.json',
   'mofchecker_log': 'logs/1ff62550d139facd6dca5644b47d5eb2_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:33:52Z'},
  {'id': 132,
   'structure': 'MIFSAX_clean.cif',
   'md5': 'e2364690df886102f38d5be84d520ff0',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'e2364690df886102f38d5be84d520ff0_mofchecker.json',
   'mofchecker_log': 'logs/e2364690df886102f38d5be84d520ff0_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:02Z'},
  {'id': 133,
   'structure': 'MOLRIP_clean.cif',
   'md5': 'dab9113849bf5da546e580df8c374671',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'dab9113849bf5da546e580df8c374671_mofchecker.json',
   'mofchecker_log': 'logs/dab9113849bf5da546e580df8c374671_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:07Z'},
  {'id': 134,
   'structure': 'MOTMAK.cif',
   'md5': 'b701450ed7c226620510e27245674b13',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'b701450ed7c226620510e27245674b13_mofchecker.json',
   'mofchecker_log': 'logs/b701450ed7c226620510e27245674b13_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:12Z'},
  {'id': 135,
   'structure': 'MUGXIX_clean.cif',
   'md5': 'da58fd555696cddd4768871940015236',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'da58fd555696cddd4768871940015236_mofchecker.json',
   'mofchecker_log': 'logs/da58fd555696cddd4768871940015236_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:17Z'},
  {'id': 136,
   'structure': 'NARPOO_clean.cif',
   'md5': 'bdd4ffa4c3fdf1503ee89ca981699692',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'bdd4ffa4c3fdf1503ee89ca981699692_mofchecker.json',
   'mofchecker_log': 'logs/bdd4ffa4c3fdf1503ee89ca981699692_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:21Z'},
  {'id': 137,
   'structure': 'NEPWIQ_clean.cif',
   'md5': 'c916cda073c1c25037f748a836caad02',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'c916cda073c1c25037f748a836caad02_mofchecker.json',
   'mofchecker_log': 'logs/c916cda073c1c25037f748a836caad02_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:25Z'},
  {'id': 138,
   'structure': 'NOCLUN_clean.cif',
   'md5': '6bb3f63ed642f5c7f7d43e3492fbc10b',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '6bb3f63ed642f5c7f7d43e3492fbc10b_mofchecker.json',
   'mofchecker_log': 'logs/6bb3f63ed642f5c7f7d43e3492fbc10b_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:29Z'},
  {'id': 139,
   'structure': 'NOCYUB_clean.cif',
   'md5': '4ecc397155accf02154f90541ddb466c',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '4ecc397155accf02154f90541ddb466c_mofchecker.json',
   'mofchecker_log': 'logs/4ecc397155accf02154f90541ddb466c_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:34Z'},
  {'id': 140,
   'structure': 'NaCl_P1.cif',
   'md5': '8bff40507b0e9a9fbda85a76db389288',
   'is_mof': True,
   'MOFQ': False,
   'mofq_reason': 'check_failed:has_carbon',
   'mofchecker_blob': '8bff40507b0e9a9fbda85a76db389288_mofchecker.json',
   'mofchecker_log': 'logs/8bff40507b0e9a9fbda85a76db389288_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:38Z'},
  {'id': 141,
   'structure': 'NbOFFIVE-1-Ni.cif',
   'md5': '366d11663de616d0147c6a15a4c3cafb',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '366d11663de616d0147c6a15a4c3cafb_mofchecker.json',
   'mofchecker_log': 'logs/366d11663de616d0147c6a15a4c3cafb_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:42Z'},
  {'id': 142,
   'structure': 'ODAJAG_clean.cif',
   'md5': 'b22cd9d887260045cd811541a58d861f',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'b22cd9d887260045cd811541a58d861f_mofchecker.json',
   'mofchecker_log': 'logs/b22cd9d887260045cd811541a58d861f_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:46Z'},
  {'id': 143,
   'structure': 'OSAVUA_clean.cif',
   'md5': 'e7f1573744a1685c46ec96622cc28893',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'e7f1573744a1685c46ec96622cc28893_mofchecker.json',
   'mofchecker_log': 'logs/e7f1573744a1685c46ec96622cc28893_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:50Z'},
  {'id': 144,
   'structure': 'OZAVES_clean.cif',
   'md5': '7a6020b6410101514a97f35370bb6784',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '7a6020b6410101514a97f35370bb6784_mofchecker.json',
   'mofchecker_log': 'logs/7a6020b6410101514a97f35370bb6784_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:54Z'},
  {'id': 145,
   'structure': 'PAMHES01_clean.cif',
   'md5': '131cd977840473ff012c1402dc45d084',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '131cd977840473ff012c1402dc45d084_mofchecker.json',
   'mofchecker_log': 'logs/131cd977840473ff012c1402dc45d084_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:34:59Z'},
  {'id': 146,
   'structure': 'PEGPUO_clean.cif',
   'md5': 'e6c3ffe36ee691fe3ba687e0666fa17b',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'e6c3ffe36ee691fe3ba687e0666fa17b_mofchecker.json',
   'mofchecker_log': 'logs/e6c3ffe36ee691fe3ba687e0666fa17b_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:35:04Z'},
  {'id': 147,
   'structure': 'PEGQAV_clean.cif',
   'md5': '7f1f9f0f649edd08c4f99154eb96f4d2',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '7f1f9f0f649edd08c4f99154eb96f4d2_mofchecker.json',
   'mofchecker_log': 'logs/7f1f9f0f649edd08c4f99154eb96f4d2_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:35:09Z'},
  {'id': 148,
   'structure': 'QATRAG_clean.cif',
   'md5': 'b175ebef08e023ae82ad1f0eacb23286',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': 'b175ebef08e023ae82ad1f0eacb23286_mofchecker.json',
   'mofchecker_log': 'logs/b175ebef08e023ae82ad1f0eacb23286_mofchecker.log',
   'mofchecker_updated_at': '2026-01-20T18:35:13Z'},
  {'id': 149,
   'structure': 'RANNUS_clean.cif',
   'md5': '233269f872b1a5d8d331a4a3cc4ec0cb',
   'is_mof': True,
   'MOFQ': True,
   'mofq_reason': None,
   'mofchecker_blob': '233269f872b1a5d8d331a4a3cc4ec0cb_mofchecker.json',
   'mofchecker_log': 'logs/233269f872b1a5d8d331a4a3cc4ec0cb_mofchecker.log',

In [10]:
df = pd.read_csv('../../AutoPrism/results/zeopp_metrics.csv')
api.update_zeopp_metrics(df)

{'created_count': 0,
 'updated_count': 284,
 'error_count': 0,
 'created_records': [],
 'updated_records': [{'id': 285,
   'mof': '05000N2_ddec',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 3.6688,
   'Df': 2.21636,
   'Dif': 3.6688,
   'largest_included_sphere_diameter': 3.6688,
   'largest_free_sphere_diameter': 2.21636,
   'largest_included_sphere_diameter_along_free_sphere_path': 3.6688,
   'ASA_m2_per_g': 0.0,
   'POAV_cm3_per_g': 0.0,
   'POAV_fraction': 0.0,
   'Density_g_cm3': 1.04938},
  {'id': 286,
   'mof': '05000N2_ddec',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 3.6688,
   'Df': 2.21636,
   'Dif': 3.6688,
   'largest_included_sphere_diameter': 3.6688,
   'largest_free_sphere_diameter': 2.21636,
   'largest_included_sphere_diameter_along_free_sphere_path': 3.6688,
   'ASA_m2_per_g': 0.0,
   'POAV_cm3_per_g': 0.0,
   'POAV_fraction': 0.0,
   'Density_g_cm3': 1.04938},
  {'id': 287,
   'mof': '05000N2_ddec',
   'md5': '38fa1a4a57d75602d1f962e5be326796',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 3.6688,
   'Df': 2.21636,
   'Dif': 3.6688,
   'largest_included_sphere_diameter': 3.6688,
   'largest_free_sphere_diameter': 2.21636,
   'largest_included_sphere_diameter_along_free_sphere_path': 3.6688,
   'ASA_m2_per_g': 0.0,
   'POAV_cm3_per_g': 0.0,
   'POAV_fraction': 0.0,
   'Density_g_cm3': 1.04938},
  {'id': 288,
   'mof': '05001N2_ddec',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 19.34449,
   'Df': 18.71956,
   'Dif': 19.31133,
   'largest_included_sphere_diameter': 19.34449,
   'largest_free_sphere_diameter': 18.71956,
   'largest_included_sphere_diameter_along_free_sphere_path': 19.31133,
   'ASA_m2_per_g': 1943.61,
   'POAV_cm3_per_g': 1.09046,
   'POAV_fraction': 0.63845,
   'Density_g_cm3': 0.585485},
  {'id': 289,
   'mof': '05001N2_ddec',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 19.34449,
   'Df': 18.71956,
   'Dif': 19.31133,
   'largest_included_sphere_diameter': 19.34449,
   'largest_free_sphere_diameter': 18.71956,
   'largest_included_sphere_diameter_along_free_sphere_path': 19.31133,
   'ASA_m2_per_g': 1926.54,
   'POAV_cm3_per_g': 1.08935,
   'POAV_fraction': 0.6378,
   'Density_g_cm3': 0.585485},
  {'id': 290,
   'mof': '05001N2_ddec',
   'md5': 'd09dd23c55c78b140591d8566883ebbc',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 19.34449,
   'Df': 18.71956,
   'Dif': 19.31133,
   'largest_included_sphere_diameter': 19.34449,
   'largest_free_sphere_diameter': 18.71956,
   'largest_included_sphere_diameter_along_free_sphere_path': 19.31133,
   'ASA_m2_per_g': 1886.82,
   'POAV_cm3_per_g': 1.08669,
   'POAV_fraction': 0.63624,
   'Density_g_cm3': 0.585485},
  {'id': 291,
   'mof': '07000N2_ddec',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 25.77046,
   'Df': 25.37246,
   'Dif': 25.77046,
   'largest_included_sphere_diameter': 25.77046,
   'largest_free_sphere_diameter': 25.37246,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.77046,
   'ASA_m2_per_g': 2166.21,
   'POAV_cm3_per_g': 1.53957,
   'POAV_fraction': 0.70522,
   'Density_g_cm3': 0.458062},
  {'id': 292,
   'mof': '07000N2_ddec',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 25.77046,
   'Df': 25.37246,
   'Dif': 25.77046,
   'largest_included_sphere_diameter': 25.77046,
   'largest_free_sphere_diameter': 25.37246,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.77046,
   'ASA_m2_per_g': 2141.96,
   'POAV_cm3_per_g': 1.53839,
   'POAV_fraction': 0.70468,
   'Density_g_cm3': 0.458062},
  {'id': 293,
   'mof': '07000N2_ddec',
   'md5': '17ca1f693001d5f4b62e9215cd6379eb',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 25.77046,
   'Df': 25.37246,
   'Dif': 25.77046,
   'largest_included_sphere_diameter': 25.77046,
   'largest_free_sphere_diameter': 25.37246,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.77046,
   'ASA_m2_per_g': 2119.99,
   'POAV_cm3_per_g': 1.53617,
   'POAV_fraction': 0.70366,
   'Density_g_cm3': 0.458062},
  {'id': 294,
   'mof': '07001N2_ddec',
   'md5': '07efdb27d3ccf4e78e03da044906f917',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 7.48308,
   'Df': 6.8544,
   'Dif': 7.48308,
   'largest_included_sphere_diameter': 7.48308,
   'largest_free_sphere_diameter': 6.8544,
   'largest_included_sphere_diameter_along_free_sphere_path': 7.48308,
   'ASA_m2_per_g': 1175.19,
   'POAV_cm3_per_g': 0.328785,
   'POAV_fraction': 0.36174,
   'Density_g_cm3': 1.10023},
  {'id': 295,
   'mof': '07001N2_ddec',
   'md5': '07efdb27d3ccf4e78e03da044906f917',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 7.48308,
   'Df': 6.8544,
   'Dif': 7.48308,
   'largest_included_sphere_diameter': 7.48308,
   'largest_free_sphere_diameter': 6.8544,
   'largest_included_sphere_diameter_along_free_sphere_path': 7.48308,
   'ASA_m2_per_g': 1144.12,
   'POAV_cm3_per_g': 0.32733,
   'POAV_fraction': 0.36014,
   'Density_g_cm3': 1.10023},
  {'id': 296,
   'mof': '07001N2_ddec',
   'md5': '07efdb27d3ccf4e78e03da044906f917',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 7.48308,
   'Df': 6.8544,
   'Dif': 7.48308,
   'largest_included_sphere_diameter': 7.48308,
   'largest_free_sphere_diameter': 6.8544,
   'largest_included_sphere_diameter_along_free_sphere_path': 7.48308,
   'ASA_m2_per_g': 1094.72,
   'POAV_cm3_per_g': 0.324604,
   'POAV_fraction': 0.35714,
   'Density_g_cm3': 1.10023},
  {'id': 297,
   'mof': '08000N3_ddec',
   'md5': '1da8a7bc1aa56632455c6c2b643c2d7c',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 9.64939,
   'Df': 5.36331,
   'Dif': 9.59433,
   'largest_included_sphere_diameter': 9.64939,
   'largest_free_sphere_diameter': 5.36331,
   'largest_included_sphere_diameter_along_free_sphere_path': 9.59433,
   'ASA_m2_per_g': 4443.69,
   'POAV_cm3_per_g': 1.22978,
   'POAV_fraction': 0.63947,
   'Density_g_cm3': 0.519987},
  {'id': 298,
   'mof': '08000N3_ddec',
   'md5': '1da8a7bc1aa56632455c6c2b643c2d7c',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 9.64939,
   'Df': 5.36331,
   'Dif': 9.59433,
   'largest_included_sphere_diameter': 9.64939,
   'largest_free_sphere_diameter': 5.36331,
   'largest_included_sphere_diameter_along_free_sphere_path': 9.59433,
   'ASA_m2_per_g': 4402.84,
   'POAV_cm3_per_g': 1.2274,
   'POAV_fraction': 0.63823,
   'Density_g_cm3': 0.519987},
  {'id': 299,
   'mof': '08000N3_ddec',
   'md5': '1da8a7bc1aa56632455c6c2b643c2d7c',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 9.64939,
   'Df': 5.36331,
   'Dif': 9.59433,
   'largest_included_sphere_diameter': 9.64939,
   'largest_free_sphere_diameter': 5.36331,
   'largest_included_sphere_diameter_along_free_sphere_path': 9.59433,
   'ASA_m2_per_g': 4334.04,
   'POAV_cm3_per_g': 1.22401,
   'POAV_fraction': 0.63647,
   'Density_g_cm3': 0.519987},
  {'id': 300,
   'mof': '15070N2_ddec',
   'md5': 'c5c5b4ebd33465b24ded58a5d4f49b24',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 25.25256,
   'Df': 25.0315,
   'Dif': 25.25256,
   'largest_included_sphere_diameter': 25.25256,
   'largest_free_sphere_diameter': 25.0315,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.25256,
   'ASA_m2_per_g': 2355.27,
   'POAV_cm3_per_g': 1.58386,
   'POAV_fraction': 0.69542,
   'Density_g_cm3': 0.439066},
  {'id': 301,
   'mof': '15070N2_ddec',
   'md5': 'c5c5b4ebd33465b24ded58a5d4f49b24',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 25.25256,
   'Df': 25.0315,
   'Dif': 25.25256,
   'largest_included_sphere_diameter': 25.25256,
   'largest_free_sphere_diameter': 25.0315,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.25256,
   'ASA_m2_per_g': 2329.42,
   'POAV_cm3_per_g': 1.58186,
   'POAV_fraction': 0.69454,
   'Density_g_cm3': 0.439066},
  {'id': 302,
   'mof': '15070N2_ddec',
   'md5': 'c5c5b4ebd33465b24ded58a5d4f49b24',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 25.25256,
   'Df': 25.0315,
   'Dif': 25.25256,
   'largest_included_sphere_diameter': 25.25256,
   'largest_free_sphere_diameter': 25.0315,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.25256,
   'ASA_m2_per_g': 2298.2,
   'POAV_cm3_per_g': 1.57871,
   'POAV_fraction': 0.69316,
   'Density_g_cm3': 0.439066},
  {'id': 303,
   'mof': '16057N2_ddec',
   'md5': '6202432f901e6b6d68c4dd3bc2ce866c',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 21.2838,
   'Df': 20.73196,
   'Dif': 21.2838,
   'largest_included_sphere_diameter': 21.2838,
   'largest_free_sphere_diameter': 20.73196,
   'largest_included_sphere_diameter_along_free_sphere_path': 21.2838,
   'ASA_m2_per_g': 1807.74,
   'POAV_cm3_per_g': 1.06696,
   'POAV_fraction': 0.65377,
   'Density_g_cm3': 0.612741},
  {'id': 304,
   'mof': '16057N2_ddec',
   'md5': '6202432f901e6b6d68c4dd3bc2ce866c',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 21.2838,
   'Df': 20.73196,
   'Dif': 21.2838,
   'largest_included_sphere_diameter': 21.2838,
   'largest_free_sphere_diameter': 20.73196,
   'largest_included_sphere_diameter_along_free_sphere_path': 21.2838,
   'ASA_m2_per_g': 1786.48,
   'POAV_cm3_per_g': 1.06543,
   'POAV_fraction': 0.65283,
   'Density_g_cm3': 0.612741},
  {'id': 305,
   'mof': '16057N2_ddec',
   'md5': '6202432f901e6b6d68c4dd3bc2ce866c',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 21.2838,
   'Df': 20.73196,
   'Dif': 21.2838,
   'largest_included_sphere_diameter': 21.2838,
   'largest_free_sphere_diameter': 20.73196,
   'largest_included_sphere_diameter_along_free_sphere_path': 21.2838,
   'ASA_m2_per_g': 1761.47,
   'POAV_cm3_per_g': 1.06255,
   'POAV_fraction': 0.65107,
   'Density_g_cm3': 0.612741},
  {'id': 306,
   'mof': '17150N2_ddec',
   'md5': 'dcc908a9605f5f513d6a7a1d220b25ef',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 24.53845,
   'Df': 24.34771,
   'Dif': 24.53845,
   'largest_included_sphere_diameter': 24.53845,
   'largest_free_sphere_diameter': 24.34771,
   'largest_included_sphere_diameter_along_free_sphere_path': 24.53845,
   'ASA_m2_per_g': 2391.15,
   'POAV_cm3_per_g': 1.47403,
   'POAV_fraction': 0.65957,
   'Density_g_cm3': 0.447461},
  {'id': 307,
   'mof': '17150N2_ddec',
   'md5': 'dcc908a9605f5f513d6a7a1d220b25ef',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 24.53845,
   'Df': 24.34771,
   'Dif': 24.53845,
   'largest_included_sphere_diameter': 24.53845,
   'largest_free_sphere_diameter': 24.34771,
   'largest_included_sphere_diameter_along_free_sphere_path': 24.53845,
   'ASA_m2_per_g': 2375.69,
   'POAV_cm3_per_g': 1.47133,
   'POAV_fraction': 0.65836,
   'Density_g_cm3': 0.447461},
  {'id': 308,
   'mof': '17150N2_ddec',
   'md5': 'dcc908a9605f5f513d6a7a1d220b25ef',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 24.53845,
   'Df': 24.34771,
   'Dif': 24.53845,
   'largest_included_sphere_diameter': 24.53845,
   'largest_free_sphere_diameter': 24.34771,
   'largest_included_sphere_diameter_along_free_sphere_path': 24.53845,
   'ASA_m2_per_g': 2344.12,
   'POAV_cm3_per_g': 1.46808,
   'POAV_fraction': 0.65691,
   'Density_g_cm3': 0.447461},
  {'id': 309,
   'mof': '19020N3_ddec',
   'md5': '9d1d4333c36c84121f85fd95f7112c6e',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 11.42647,
   'Df': 8.65437,
   'Dif': 10.84008,
   'largest_included_sphere_diameter': 11.42647,
   'largest_free_sphere_diameter': 8.65437,
   'largest_included_sphere_diameter_along_free_sphere_path': 10.84008,
   'ASA_m2_per_g': 6572.82,
   'POAV_cm3_per_g': 2.50335,
   'POAV_fraction': 0.80817,
   'Density_g_cm3': 0.322836},
  {'id': 310,
   'mof': '19020N3_ddec',
   'md5': '9d1d4333c36c84121f85fd95f7112c6e',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 11.42647,
   'Df': 8.65437,
   'Dif': 10.84008,
   'largest_included_sphere_diameter': 11.42647,
   'largest_free_sphere_diameter': 8.65437,
   'largest_included_sphere_diameter_along_free_sphere_path': 10.84008,
   'ASA_m2_per_g': 6585.3,
   'POAV_cm3_per_g': 2.50102,
   'POAV_fraction': 0.80742,
   'Density_g_cm3': 0.322836},
  {'id': 311,
   'mof': '19020N3_ddec',
   'md5': '9d1d4333c36c84121f85fd95f7112c6e',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 11.42647,
   'Df': 8.65437,
   'Dif': 10.84008,
   'largest_included_sphere_diameter': 11.42647,
   'largest_free_sphere_diameter': 8.65437,
   'largest_included_sphere_diameter_along_free_sphere_path': 10.84008,
   'ASA_m2_per_g': 6604.96,
   'POAV_cm3_per_g': 2.49672,
   'POAV_fraction': 0.80603,
   'Density_g_cm3': 0.322836},
  {'id': 312,
   'mof': '20051N2_ddec',
   'md5': '7409057b99b5ac68066d923ded4ca2a8',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 26.51283,
   'Df': 26.20962,
   'Dif': 26.51025,
   'largest_included_sphere_diameter': 26.51283,
   'largest_free_sphere_diameter': 26.20962,
   'largest_included_sphere_diameter_along_free_sphere_path': 26.51025,
   'ASA_m2_per_g': 2208.46,
   'POAV_cm3_per_g': 1.50034,
   'POAV_fraction': 0.69444,
   'Density_g_cm3': 0.462854},
  {'id': 313,
   'mof': '20051N2_ddec',
   'md5': '7409057b99b5ac68066d923ded4ca2a8',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 26.51283,
   'Df': 26.20962,
   'Dif': 26.51025,
   'largest_included_sphere_diameter': 26.51283,
   'largest_free_sphere_diameter': 26.20962,
   'largest_included_sphere_diameter_along_free_sphere_path': 26.51025,
   'ASA_m2_per_g': 2186.72,
   'POAV_cm3_per_g': 1.49872,
   'POAV_fraction': 0.69369,
   'Density_g_cm3': 0.462854},
  {'id': 314,
   'mof': '20051N2_ddec',
   'md5': '7409057b99b5ac68066d923ded4ca2a8',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 26.51283,
   'Df': 26.20962,
   'Dif': 26.51025,
   'largest_included_sphere_diameter': 26.51283,
   'largest_free_sphere_diameter': 26.20962,
   'largest_included_sphere_diameter_along_free_sphere_path': 26.51025,
   'ASA_m2_per_g': 2156.48,
   'POAV_cm3_per_g': 1.49617,
   'POAV_fraction': 0.69251,
   'Density_g_cm3': 0.462854},
  {'id': 315,
   'mof': '20590N2_ddec',
   'md5': '735702b3d8c787aa19784f8b53bb6c9e',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 25.9921,
   'Df': 25.66617,
   'Dif': 25.9921,
   'largest_included_sphere_diameter': 25.9921,
   'largest_free_sphere_diameter': 25.66617,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.9921,
   'ASA_m2_per_g': 2315.18,
   'POAV_cm3_per_g': 1.28917,
   'POAV_fraction': 0.65066,
   'Density_g_cm3': 0.504711},
  {'id': 316,
   'mof': '20590N2_ddec',
   'md5': '735702b3d8c787aa19784f8b53bb6c9e',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 25.9921,
   'Df': 25.66617,
   'Dif': 25.9921,
   'largest_included_sphere_diameter': 25.9921,
   'largest_free_sphere_diameter': 25.66617,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.9921,
   'ASA_m2_per_g': 2261.14,
   'POAV_cm3_per_g': 1.28519,
   'POAV_fraction': 0.64865,
   'Density_g_cm3': 0.504711},
  {'id': 317,
   'mof': '20590N2_ddec',
   'md5': '735702b3d8c787aa19784f8b53bb6c9e',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 25.9921,
   'Df': 25.66617,
   'Dif': 25.9921,
   'largest_included_sphere_diameter': 25.9921,
   'largest_free_sphere_diameter': 25.66617,
   'largest_included_sphere_diameter_along_free_sphere_path': 25.9921,
   'ASA_m2_per_g': 2163.04,
   'POAV_cm3_per_g': 1.27277,
   'POAV_fraction': 0.64238,
   'Density_g_cm3': 0.504711},
  {'id': 318,
   'mof': '21030N2_ddec',
   'md5': '7366b13430080588504f0bf8bd2a387f',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 19.27673,
   'Df': 18.94015,
   'Dif': 19.27673,
   'largest_included_sphere_diameter': 19.27673,
   'largest_free_sphere_diameter': 18.94015,
   'largest_included_sphere_diameter_along_free_sphere_path': 19.27673,
   'ASA_m2_per_g': 1785.8,
   'POAV_cm3_per_g': 0.854138,
   'POAV_fraction': 0.5237,
   'Density_g_cm3': 0.613133},
  {'id': 319,
   'mof': '21030N2_ddec',
   'md5': '7366b13430080588504f0bf8bd2a387f',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 19.27673,
   'Df': 18.94015,
   'Dif': 19.27673,
   'largest_included_sphere_diameter': 19.27673,
   'largest_free_sphere_diameter': 18.94015,
   'largest_included_sphere_diameter_along_free_sphere_path': 19.27673,
   'ASA_m2_per_g': 1751.65,
   'POAV_cm3_per_g': 0.851936,
   'POAV_fraction': 0.52235,
   'Density_g_cm3': 0.613133},
  {'id': 320,
   'mof': '21030N2_ddec',
   'md5': '7366b13430080588504f0bf8bd2a387f',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 19.27673,
   'Df': 18.94015,
   'Dif': 19.27673,
   'largest_included_sphere_diameter': 19.27673,
   'largest_free_sphere_diameter': 18.94015,
   'largest_included_sphere_diameter_along_free_sphere_path': 19.27673,
   'ASA_m2_per_g': 1702.7,
   'POAV_cm3_per_g': 0.849702,
   'POAV_fraction': 0.52098,
   'Density_g_cm3': 0.613133},
  {'id': 321,
   'mof': '22108N2_ddec',
   'md5': 'b658efcf311744888b772d09151f8e92',
   'probe': 'CO2',
   'probe_radius': 1.525,
   'scale': 1.0,
   'block_radius': 1.525,
   'Di': 20.15565,
   'Df': 19.81714,
   'Dif': 20.15393,
   'largest_included_sphere_diameter': 20.15565,
   'largest_free_sphere_diameter': 19.81714,
   'largest_included_sphere_diameter_along_free_sphere_path': 20.15393,
   'ASA_m2_per_g': 2124.36,
   'POAV_cm3_per_g': 0.904405,
   'POAV_fraction': 0.54874,
   'Density_g_cm3': 0.606741},
  {'id': 322,
   'mof': '22108N2_ddec',
   'md5': 'b658efcf311744888b772d09151f8e92',
   'probe': 'H2O',
   'probe_radius': 1.577,
   'scale': 1.0,
   'block_radius': 1.577,
   'Di': 20.15565,
   'Df': 19.81714,
   'Dif': 20.15393,
   'largest_included_sphere_diameter': 20.15565,
   'largest_free_sphere_diameter': 19.81714,
   'largest_included_sphere_diameter_along_free_sphere_path': 20.15393,
   'ASA_m2_per_g': 2090.73,
   'POAV_cm3_per_g': 0.901488,
   'POAV_fraction': 0.54697,
   'Density_g_cm3': 0.606741},
  {'id': 323,
   'mof': '22108N2_ddec',
   'md5': 'b658efcf311744888b772d09151f8e92',
   'probe': 'N2',
   'probe_radius': 1.655,
   'scale': 1.0,
   'block_radius': 1.655,
   'Di': 20.15565,
   'Df': 19.81714,
   'Dif': 20.15393,
   'largest_included_sphere_diameter': 20.15565,
   'largest_free_sphere_diameter': 19.81714,
   'largest_included_sphere_diameter_along_free_sphere_path': 20.15393,
   'ASA_m2_per_g': 2032.92,